### ISSUE TITLE
airbnbfy 

### ISSUE THREAD

**Issue by 014ee** [014ee/algorithm#1]
**Todo List**

- [ ] textarea에 focus 시 placeholder 삭제
- [x] textarea에 텍스트 입력하면 하단에 입력된 문자 수 표기
- [x] textarea에 텍스트 입력 후 X 버튼 누르면 글자 삭제 및 문자 수 0으로 변경
- [ ] textarea에 텍스트 입력 후 변환하기 누르면 난독화 과정 거쳐서 결과 페이지에 표시
- [ ] copy 버튼 누르면 난독화된 텍스트 복사
